CREATE SEQUENCE CUST_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE CUSTOMER_POLICY_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE POLICY_SEQ START WITH 200 INCREMENT BY 1;
CREATE SEQUENCE FEEDBACK_SEQ START WITH 200 INCREMENT BY 1;

CREATE TABLE FEEDBACK( FEEDBACK_ID INT,CUSTOMER_ID INT,FEEDBACK_CONTENT VARCHAR(255),FEEDBACK_TITLE VARCHAR(255));
CREATE TABLE CUSTOMER( customer_id integer not null,address varchar(255),contact_number varchar(255),customer_name varchar(255), email varchar(255), nominee_name varchar(255), password varchar(255), relationship_with_customer varchar(255) , primary key(customer_id));
CREATE TABLE POLICY(policy_id integer, policy_title varchar(255), policy_type varchar(255), premium integer not null, sum_assured integer not null, term integer not null, primary key(policy_id));
CREATE TABLE CUSTOMER_POLICY (ID INT,CUSTOMER_ID int,POLICY_ID int, STATUS VARCHAR(20), COMMENCEMENT_DATE DATE,MATURITY_DATE DATE,NEXT_DUE_DATE DATE, insurer varchar(30));

INSERT INTO CUSTOMER (CUSTOMER_ID,ADDRESS,CONTACT_NUMBER,CUSTOMER_NAME,EMAIL,NOMINEE_NAME,PASSWORD,RELATIONSHIP_WITH_CUSTOMER) VALUES (NEXT VALUE FOR CUST_SEQ,'Hidden Leaf Village','9876534109','naruto','uzamaki@leaf.in','Hinata','pass@123','Wife');

INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Life Insurance 1','Life Insurance',100,10000,4);
INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Life Insurance 2','Life Insurance',1000,100000,8);
INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Life Insurance 3','Life Insurance',10000,1000000,12);
INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Health Insurance 1','Health Insurance',1000,100000,4);
INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Health Insurance 2','Health Insurance',1000,100000,8);
INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Health Insurance 3','Health Insurance',1000,100000,12);
INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Term Insurance 1','Term Insurance',1000,100000,3);
INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Term Insurance 2','Term Insurance',1000,100000,6);
INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Term Insurance 3','Term Insurance',1000,100000,9);


//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Life Insurance','Life Insurance 1',100,10000,4);
//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Life Insurance','Life Insurance 2',1000,100000,8);
//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Life Insurance','Life Insurance 3',10000,1000000,12);
//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Health Insurance','Health Insurance 1',1000,100000,4);
//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Health Insurance','Health Insurance 2',1000,100000,8);
//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Health Insurance','Health Insurance 3',1000,100000,12);
//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Term Insurance','Term Insurance 1',1000,100000,3);
//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Term Insurance','Term Insurance 2',1000,100000,6);
//INSERT INTO POLICY (POLICY_ID,POLICY_TITLE,POLICY_TYPE,PREMIUM,SUM_ASSURED,TERM) values (NEXT VALUE FOR POLICY_SEQ,'Term Insurance','Term Insurance 3',1000,100000,9);